In [1]:
import pandas as pd

In [12]:
import numpy as np

In [33]:
data=pd.read_csv('C:\\Users\\Vika\\Desktop\\Tutorials\\mammogram_ML.txt',header=None,na_values='?')

In [34]:
data.head()

0     1    2    3    4  5
0  5.0  67.0  3.0  5.0  3.0  1
1  4.0  43.0  1.0  1.0  NaN  1
2  5.0  58.0  4.0  5.0  3.0  1
3  4.0  28.0  1.0  1.0  3.0  0
4  5.0  74.0  1.0  5.0  NaN  1

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 6 columns):
0    959 non-null float64
1    956 non-null float64
2    930 non-null float64
3    913 non-null float64
4    885 non-null float64
5    961 non-null int64
dtypes: float64(5), int64(1)
memory usage: 45.1 KB


## Renaming the columns

In [36]:
data.columns=['BIRADS','Age','Shape','Margin','Density','Severity']

In [37]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 961 entries, 0 to 960
Data columns (total 6 columns):
BIRADS      959 non-null float64
Age         956 non-null float64
Shape       930 non-null float64
Margin      913 non-null float64
Density     885 non-null float64
Severity    961 non-null int64
dtypes: float64(5), int64(1)
memory usage: 45.1 KB


In [43]:
data.describe()

BIRADS         Age       Shape      Margin     Density    Severity
count  959.000000  956.000000  930.000000  913.000000  885.000000  961.000000
mean     4.348279   55.487448    2.721505    2.796276    2.910734    0.463059
std      1.783031   14.480131    1.242792    1.566546    0.380444    0.498893
min      0.000000   18.000000    1.000000    1.000000    1.000000    0.000000
25%      4.000000   45.000000    2.000000    1.000000    3.000000    0.000000
50%      4.000000   57.000000    3.000000    3.000000    3.000000    0.000000
75%      5.000000   66.000000    4.000000    4.000000    3.000000    1.000000
max     55.000000   96.000000    4.000000    5.000000    4.000000    1.000000

## Drop the missing values

In [45]:
data.dropna(inplace=True)
data.head()

BIRADS   Age  Shape  Margin  Density  Severity
0      5.0  67.0    3.0     5.0      3.0         1
2      5.0  58.0    4.0     5.0      3.0         1
3      4.0  28.0    1.0     1.0      3.0         0
8      5.0  57.0    1.0     5.0      3.0         1
10     5.0  76.0    1.0     4.0      3.0         1

In [46]:
data.isna().sum()

BIRADS      0
Age         0
Shape       0
Margin      0
Density     0
Severity    0
dtype: int64

## Features and Target variable arrays

In [47]:
features=data[['Age','Shape','Margin','Density']].values
classes=data['Severity'].values

In [48]:
features

array([[67.,  3.,  5.,  3.],
       [58.,  4.,  5.,  3.],
       [28.,  1.,  1.,  3.],
       ...,
       [64.,  4.,  5.,  3.],
       [66.,  4.,  5.,  3.],
       [62.,  3.,  3.,  3.]])

## Sklearn imports & scaling the data

In [72]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier

In [50]:
scaler=preprocessing.StandardScaler()

In [52]:
scaled_features=scaler.fit_transform(features)
scaled_features

array([[ 0.7650629 ,  0.17563638,  1.39618483,  0.24046607],
       [ 0.15127063,  0.98104077,  1.39618483,  0.24046607],
       [-1.89470363, -1.43517241, -1.157718  ,  0.24046607],
       ...,
       [ 0.56046548,  0.98104077,  1.39618483,  0.24046607],
       [ 0.69686376,  0.98104077,  1.39618483,  0.24046607],
       [ 0.42406719,  0.17563638,  0.11923341,  0.24046607]])

## Splitting the data into 75% training and 25% test data

In [53]:
X_train,X_test,y_train,y_test=train_test_split(scaled_features,classes,train_size=0.75,random_state=1)

C:\Users\Vika\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [94]:
## DECSISION TREE

In [67]:
tree1=DecisionTreeClassifier(random_state=1)

In [68]:
tree1.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best')

In [69]:
tree1.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [70]:
tree1.score(X_test,y_test)

0.7355769230769231

In [96]:
## K-fold cross validation

In [73]:
cv_score=cross_val_score(tree1, scaled_features,classes,cv=10)
cv_score.mean()

0.7373556945552244

In [95]:
## RANDOM FOREST

In [74]:
from sklearn.ensemble import RandomForestClassifier

In [76]:
RF=RandomForestClassifier(n_estimators=10, random_state=1,)
cv_score=cross_val_score(RF,scaled_features,classes,cv=10)
cv_score.mean()

0.7540496480696304

In [97]:
## SVM

In [78]:
from sklearn import svm
C = 1.0
svc = svm.SVC(kernel='linear', C=C)

In [79]:
cv_score=cross_val_score(svc,scaled_features,classes,cv=10)
cv_score.mean()

0.7964988875362076

In [83]:
svc = svm.SVC(kernel='rbf', C=C)
cv_score=cross_val_score(svc,scaled_features,classes,cv=10)
cv_score.mean()

0.8012023704574396

In [84]:
svc = svm.SVC(kernel='sigmoid', C=C)
cv_score=cross_val_score(svc,scaled_features,classes,cv=10)
cv_score.mean()

0.7351055791108685

In [85]:
svc = svm.SVC(kernel='poly', C=C)
cv_score=cross_val_score(svc,scaled_features,classes,cv=10)
cv_score.mean()

0.792753942599667

In [98]:
## KNN CLASSIFIER

In [82]:
for n in range(1,51):
    knn=KNeighborsClassifier(n_neighbors=n)
    cv_score=cross_val_score(knn,scaled_features,classes,cv=10)
    print(n,cv_score.mean())

1 0.7239123742356184
2 0.6889838098036746
3 0.7541080699103032
4 0.7300813008130081
5 0.7735464506108056
6 0.7626163189342738
7 0.7940595133145824
8 0.7747082406280172
9 0.7880200243482641
10 0.7854795488574507
11 0.7915333809104012
12 0.7794257168045002
13 0.7819084701174035
14 0.7915039950743742
15 0.7878748443250353
16 0.7794411093852764
17 0.7818073688482151
18 0.775681121699341
19 0.7805147418944068
20 0.7828666582707136
21 0.7853927906748946
22 0.7817342540895289
23 0.7805588206484475
24 0.780587506821712
25 0.7878171221471251
26 0.7866269957880302
27 0.7854365195975539
28 0.7902271105327232
29 0.7865979597833844
30 0.7878314652337574
31 0.7914172368918182
32 0.7878314652337574
33 0.7865976099520032
34 0.7866119530386354
35 0.7866262961252677
36 0.7854358199347914
37 0.7866843681345592
38 0.7866553321299133
39 0.7878891874116676
40 0.7854791990260694
41 0.7854645061080558
42 0.7818500482767305
43 0.7830692106404713
44 0.783054867553839
45 0.783054867553839
46 0.7854648559394373
4

In [99]:
## NAIVE BAYES CLASSIFIER

In [89]:
from sklearn.naive_bayes import MultinomialNB

scaler = preprocessing.MinMaxScaler()
all_features_minmax = scaler.fit_transform(features)

NB=MultinomialNB()
cv_score=cross_val_score(NB,all_features_minmax,classes,cv=10)
cv_score.mean()

0.7844055665169388

In [ ]:
## LINEAR & LOGISTIC REGRESSION

In [92]:
from sklearn.linear_model import LogisticRegression, LinearRegression
LR=LogisticRegression()
LR1=LinearRegression()
cv_score=cross_val_score(LR,scaled_features,classes,cv=10)
cv_score.mean()

0.8073583532737221

In [93]:
cv_score=cross_val_score(LR1,scaled_features,classes,cv=10)
cv_score.mean()

0.4029016226042389

## Linear Regression and Decision Trees have less accuracy and hyperpameter tuning might result in much better results